### ISSUE TITLE
Add to CKAN?

### ISSUE THREAD

**Issue by NathanKell** [Nazfib/TransferWindowPlanner#1]
@Nazfib I'd love to rec this mod as part of the RP-1 express install. Can you (or would you mind if we) added it to CKAN?

**Comment by Nazfib** [comment]
I am not opposed in principle, but
- Without Mechjeb (or kOS) there is no way to launch into a specific LAN; since there is currently no way to visualize what the parking orbit looks like, for "stock" users, the old version will be easier to use.
- I should probably either fix or remove the version checker (it points to TriggerAu's version).
- As far as I know, TriggerAu was planning on publishing an update himself (from a comment on the forums), but that was already a few months ago.

In my opinion, as long as it is clearly marked as a fork instead of a straight update to the original, I'm fine with it being on CKAN. Do you have time to set that up? Otherwise, I'll look into it this weekend.

**Comment by NathanKell** [comment]
Would it be worth releasing it as TWP-RSS Edition or something then? That both makes it clear it's a fork and makes it clear that it's for non-stock systems.
Agree about changing the .version to point to your own.

I'll PM Trigger, eight months (or so) ago he said he was gonna update but I think life has just been too busy (understandably!)

**Comment by HebaruSan** [comment]
@NathanKell, this is in CKAN now with identifier `TransferWindowPlannerFork` if you want to add it.

https://github.com/KSP-CKAN/CKAN-meta/commit/64f4141dbc2921bd47be57c4db7f0124880e56e0

**Comment by NathanKell** [comment]
Sweet!

Yeah about ~6mo ago I was speaking with Trigger and he said he was going to bump compat shortly but was fairly busy (and would take a peek at this fork). Reached out again a month ago and haven't heard back. I think forking makes sense anyway since the functionality is different, but especially in this case.

**Comment by NathanKell** [comment]
Oh lol I'm on the TWP issue page not the CKAN issue page, where the above is discussed anyway.
