### ISSUE TITLE
"No TWP Phase and Eject Angle found in notes"

### ISSUE THREAD

**Issue by bofhgr** [Nazfib/TransferWindowPlanner#2]
Thank you for the adaptation of this wonderful mod for RSS - super useful!!!

I get the error in the title when I click on the alarm details - using ver 1.9.0.0 - I don't see the phase angle when I turn on the map view.
Running RP-1 with express install + Principia on KSP 1.12.3.

Otherwise it seems to be working fine and the calculations are quite fine to work with, the helper in the map would be a bonus to see the parking orbit but I suppose it is limited in doing so because I run Principia?

![image](https://user-images.githubusercontent.com/28956359/160106171-ce6a072a-0db2-422b-84bb-4b9a55be029f.png)

Screenshot if it helps - I can also provide logs and whatever else you'd need to help troubleshoot.

**Comment by Nazfib** [comment]
Ah, this is annoying. It looks like KAC searches the text in the alarm for the eject angle, and then has a copy of the old code in TWP to draw the eject and phase angles. Since I changed both of these, someone will have to change KAC to match. Unfortunately, I can't fix this in TWP. Whoever eventually adopts KAC will have to change it on their side.

As a workaround, I guess the easiest way is to recreate the transfer in TWP's window; the buttons in TWP will work properly.
